import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import { StoreProvider } from './StoreProvider';
import { MasterLayout } from '@/components/layout/MasterLayout';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['300', '400', '500', '700'],
});
export const metadata: Metadata = {
  title: 'Aha Frontend Exam | Nazhat Adiba',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={ubuntu.className}>
          <MasterLayout>{children}</MasterLayout>
        </body>
      </StoreProvider>
    </html>
  );
}
