import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/navigation/SideBar";
import ReduxProvider from "@/provider/ReduxProvider";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["300", "400", "500", "700"],
});
export const metadata: Metadata = {
  title: "Aha Frontend Exam | Nazhat Adiba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={ubuntu.className}>
          <SideBar />
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
